CREATE TABLE "AbriendoCaminos"."INGRESOS" (
	"ID" NUMBER NOT NULL ENABLE, 
	"ID_INTERNO" NUMBER NOT NULL ENABLE, 
	"ID_DOMICILIO_PART" NUMBER NOT NULL ENABLE, 
	"ID_DOMICILIO_TRAB" NUMBER NOT NULL ENABLE, 
	"ID_FAM_RESP" NUMBER NOT NULL ENABLE, 
	"TIPO_INGRESO" VARCHAR2(150 BYTE), 
	"PROVIENE" VARCHAR2(250 BYTE), 
	"ACUDE" VARCHAR2(250 BYTE), 
	"REVISION" VARCHAR2(250 BYTE), 
	"PRESENTA" VARCHAR2(250 BYTE), 
	"DROGAS" VARCHAR2(250 BYTE), 
	"OBSERVACIONES" VARCHAR2(250 BYTE), 
	"APORTACION" VARCHAR2(250 BYTE), 
	CONSTRAINT "INGRESOS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "INGRESOS_DOM_PART_FK" FOREIGN KEY ("ID_DOMICILIO_PART")
	  REFERENCES "AbriendoCaminos"."DOMICILIOS_PART" ("ID") ENABLE, 
	 CONSTRAINT "INGRESOS_DOM_TRAB_FK" FOREIGN KEY ("ID_DOMICILIO_TRAB")
	  REFERENCES "AbriendoCaminos"."DOMICILIOS_TRAB" ("ID") ENABLE, 
	 CONSTRAINT "INGRESOS_FAM_RESP_FK" FOREIGN KEY ("ID_FAM_RESP")
	  REFERENCES "AbriendoCaminos"."FAM_RESP" ("ID") ENABLE, 
	 CONSTRAINT "INGRESOS_INTERNO_FK" FOREIGN KEY ("ID_INTERNO")
	  REFERENCES "AbriendoCaminos"."INTERNOS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE TABLE "AbriendoCaminos"."DOMICILIOS_PART" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_INGRESO" NUMBER NOT NULL ENABLE, 
	"CALLE" VARCHAR2(500 BYTE), 
	"NUMERO" VARCHAR2(10 BYTE), 
	"COLONIA_POB" VARCHAR2(250 BYTE), 
	"MUNICIPIO_DEL" VARCHAR2(250 BYTE), 
	"ENTIDAD_FED" VARCHAR2(250 BYTE), 
	"CP" VARCHAR2(5 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "DOMICILIOS_PART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "INGRESO_FK1" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "AbriendoCaminos"."INGRESOS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE TABLE "AbriendoCaminos"."INTERNOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_INGRESO" NUMBER NOT NULL ENABLE, 
	"ID_EGRESO" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"AP_PATERNO" VARCHAR2(20 BYTE), 
	"AP_MATERNO" VARCHAR2(20 BYTE), 
	"EDAD" NUMBER, 
	"SEXO" VARCHAR2(20 BYTE), 
	"FECHA_NAC" VARCHAR2(20 BYTE), 
	"ESTADO_CIVIL" VARCHAR2(20 BYTE), 
	"ESCOLARIDAD" VARCHAR2(20 BYTE), 
	"OCUPACION" VARCHAR2(20 BYTE), 
	"SERV_MED" VARCHAR2(20 BYTE), 
	"NSS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "INTERNOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "INTERNOS_INGRESOS_FK" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "AbriendoCaminos"."INGRESOS" ("ID") ENABLE, 
	 CONSTRAINT "INTERNOS_EGRESOS_FK" FOREIGN KEY ("ID_EGRESO")
	  REFERENCES "AbriendoCaminos"."EGRESOS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE TABLE "AbriendoCaminos"."EGRESOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_INTERNO" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"AP_PATERNO" VARCHAR2(20 BYTE), 
	"AP_MATERNO" VARCHAR2(20 BYTE), 
	"EDAD" VARCHAR2(20 BYTE), 
	"SEXO" VARCHAR2(20 BYTE), 
	"FECHA_NAC" VARCHAR2(20 BYTE), 
	"ESTADO_CIVIL" VARCHAR2(20 BYTE), 
	"ESCOLARIDAD" VARCHAR2(20 BYTE), 
	"OCUPACION" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"ESTADO_GRAL" VARCHAR2(20 BYTE), 
	 CONSTRAINT "EGRESOS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "AbriendoCaminos"."TABLE1_PK1" ON "AbriendoCaminos"."EGRESOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSTEM" )  ENABLE, 
	 CONSTRAINT "EGRESOS_INTERNOS_FK" FOREIGN KEY ("ID_INTERNO")
	  REFERENCES "AbriendoCaminos"."INTERNOS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE TABLE "AbriendoCaminos"."FAM_RESP" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_INGRESO" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"AP_PATERNO" VARCHAR2(20 BYTE), 
	"AP_MATERNO" VARCHAR2(20 BYTE), 
	"CALLE" VARCHAR2(250 BYTE), 
	"NUMERO" VARCHAR2(5 BYTE), 
	"COLONIA_POB" VARCHAR2(250 BYTE), 
	"MUNICIPIO_DEL" VARCHAR2(250 BYTE), 
	"ENTIDAD_FED" VARCHAR2(250 BYTE), 
	"CP" VARCHAR2(5 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "FAM_RESP_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "AbriendoCaminos"."TABLE1_PK2" ON "AbriendoCaminos"."FAM_RESP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSTEM" )  ENABLE, 
	 CONSTRAINT "FAM_RESP_FK1" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "AbriendoCaminos"."INGRESOS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE TABLE "AbriendoCaminos"."DOMICILIOS_TRAB" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_INGRESO" NUMBER, 
	"CALLE" VARCHAR2(500 BYTE), 
	"NUMERO" VARCHAR2(10 BYTE), 
	"COLONIA_POB" VARCHAR2(250 BYTE), 
	"MUNICIPIO_DEL" VARCHAR2(250 BYTE), 
	"ENTIDAD_FED" VARCHAR2(250 BYTE), 
	"CP" VARCHAR2(5 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "DOMICILIOS_TRAB_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "AbriendoCaminos"."TABLE1_PK3" ON "AbriendoCaminos"."DOMICILIOS_TRAB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSTEM" )  ENABLE, 
	 CONSTRAINT "DOMICILIOS_TRAB_FK1" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "AbriendoCaminos"."INGRESOS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
